create table courtAuctionInfo(
CLTR_MNMT_NO VARCHAR(50)
,CTGR_FULL_NM VARCHAR(100)
,LDNM_ADRS	VARCHAR(1000)
,PBCT_BEGN_DTM VARCHAR(14)
,PBCT_CLS_DTM VARCHAR(14)
,PBCT_CLTR_STAT_NM VARCHAR(100)
,USCBD_CNT integer
,IQRY_CNT integer
,GOODS_NM VARCHAR(4000)
,BID_MTD_NM VARCHAR(100)
,MIN_BID_PRC integer
,FEE_RATE VARCHAR(10)
,APSL_ASES_AVG_AMT integer
);